---
title: "CLASE"
author: "Karina Álvarez"
date: "2025-10-14"
output: html_document
---

### BARRA

```{r}
library(ggplot2)
```

```{r}
data("DNase")
head(DNase,3)
```

```{r}
mean_density<- aggregate(density ~ conc, data = DNase, FUN = mean)
mean_density
```


```{r}
barplot(
  height = mean_density$density,
  names.arg = mean_density$conc,
  col = "lightblue",
  border= "gray30",
  main = "Mean DNase I Activity by Concentration",
  xlab= "Concentration (mg/mL)",
  ylab = "Mean Optical Density",
  las = 2,
  cex.names = 0.8
)
```


### LINEAR

```{r}
data (co2)
head (co2, 5)
```

```{r}
plot(
  co2 ~ time(co2),
  type= "l",
  col= "blue",
  lwd = 2,
  xlab = "Year",
  ylab = "CO2 Concentration (ppm)",
  main = "Atmospheric CO2 Concentration (1958-1998)"
)
```

```{r}
co2_data <- data.frame(
  time = as.numeric(time(co2)),
  co2= as.numeric(co2)
)
```

```{r}
spearman_result <- cor.test(
  co2_data$time,
  co2_data$co2,
  method = "spearman",
  exact = FALSE
)
```

```{r}
spearman_result
```

```{r}
shapiro.test(co2_data$co2)
```


```{r}
plot(
  co2 ~ time(co2),
  type= "l",
  col= "blue",
  lwd = 2,
  xlab = "Year",
  ylab = "CO2 Concentration (ppm)",
  main = "Atmospheric CO2 Concentration (1958-1998)"
)

abline(lm(co2_data$co2 ~ co2_data$time), col= "red", lwd = 2, lty = 2)
```



Continucación:

```{r}
library(readxl)
coronary<-read_excel(practicas/coronary.xlsx)
coronary
head(coronary,3)
```


```{r}
plot(
  coronary$dbp ~ coronary$chol,
  type = "p",
  col = "#e34e33",
  lwd= 2,
  xlab= "Total Cholesterol (mmol/L)",
  ylab= "Diastolic Blood Pressure (mmHg)",
  main= "Relationship between Cholesterol and Diastolic BP"
)
```

