---
title: "Practica 1"
author: "Karina Álvarez"
date: "2025-09-04"
output: html_document
---


```{r, cite}
#Esto es para tomar la cita para nuestros artículos.
citation()

```

```{r, instalar paquetes }
#Instalar paquetes
#install.packages('ggplot2')
#install.packages("dplyr")
#para instalar paquetes de una vez: install.packages(c("dplyr","ggplot2"))
```

```{r, message=FALSE}
library(ggplot2)
library(dplyr)
```

```{r, citar los paquetes}
citation("dplyr")
citation("ggplot2")
```

```{r, help}
#Ayuda para entender las grapicas etc.
?lm
??ggplot2
```

```{r equivalencias}
1 == 2 
"Karina"=="karina"
"karina"!="Karina"
5<6
6>5
```

```{r, asignar valores}
a <- 45
a
```

```{r asignar valores}
a <- 45
a
48 -> b
b

a + b / a
c <- a + b
c

a + b + c / c
d <- a + b /a

a + b / d * c

x <- "tambien puede ser una frase"
x
```

```{r, ecuaciones matematicas}
sqrt (16)
abs (-5)
log (10)
exp (2)
```


```{r variables}
var1 <- 10 
var2 <- 20
var1 
var1 + var2 
var3 <- var1 + var2
var3
```

```{r verificar class}
class(var3)
class(x)
```

```{r, system}
x <-Sys.time()
x
class(x)
```

